### PR TITLE
Simonbray compchem

### PR DESCRIPTION
**Pull request by chrisbarnettster**

### CODE REVIEW

**Comment by simonbray** [comment]
Thanks!

Can you also merge into the compchem branch? Then the new commits should appear here as well: https://github.com/galaxyproject/training-material/pull/1202

**Comment by simonbray** [comment]
ping @chrisbarnettster

**Comment by chrisbarnettster** [comment]
@simonbray  Yes I didn't get those notifications previously.... Must have turned them off. 
Will do so.

**Comment by simonbray** [comment]
Hi @chrisbarnettster, could you perform this merge? Keen to get the new tutorial into the training material repo as soon as we can. :)

**Comment by chrisbarnettster** [comment]
Hi @simonbray

I've pulled upstream, Fixing up some copyright issues with images and then
will be ready today :)

All the best,
C

**Comment by chrisbarnettster** [comment]
@simonbray see galaxyproject/training-material/#1378

**Comment by simonbray** [comment]
Thanks!

**Pull request merged**
